_target_: pytorch_lightning.Trainer

defaults:
  - default

gpus: 4

resume_from_checkpoint:
auto_lr_find: False
deterministic: True
accelerator: dp
sync_batchnorm: False

max_epochs: 3000
min_epochs: 1
check_val_every_n_epoch: 10
num_sanity_val_steps: 1

precision: 16
amp_backend: "native"
amp_level: "O2"