_target_: src.models.mdxnet.ConvTDFNet

target_name: 'drums'

# model
num_blocks: 11
l: 3
g: 32
k: 3
bn: 8
bias: False

# stft
n_fft: 4096
dim_f: 2048
dim_t: 256
dim_c: 4
hop_length: 1024

overlap: 2048

# optimizer
lr: 0.0001
optimizer: rmsprop